### ISSUE TITLE
[suggestion] CC65 compiler option -Cl

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [iss000/oricCompilerBenchmark#1]
Maybe it would be interesting to test CC65 with a commonly used optimizer option -Cl, which makes all local variables static. This breaks recursive calls but on 8-bit systems, they are seldomly used.

**Comment by iss000** [comment]
Thanks @Fabrizio-Caruso !
I'm preparing very updated version with more compilers and tests.
Stay tuned ;)
