### ISSUE TITLE
How do I build with your Makefile? It cannot find the lib file under Cygwin/Windows

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [iss000/oricCompilerBenchmark#2]
I have tried to use your makefile (after updating the CC65 variable) to build your test for the cc65 only.
It fails with an error about not being able to find the lib file despite using the correct path:
![image](https://user-images.githubusercontent.com/29057615/175676371-66eb8df5-0a63-4b62-b945-d8bf33c698f7.png)

**Comment by iss000** [comment]
Can you try under Linux or Mingw?

**Comment by Fabrizio-Caruso** [comment]
It works fine under the Windows subsystem for Linux. The problem seems to be the linker. It fails to find the lib. This is probably a Cygwin issue or a CC65 issue under Cygwin. By the way, one extra thing may be the cause: I use Windows CC65 and not Cygwin CC65 under Cygwin. No problem with cl65 for me so far in 5 years.

**Comment by iss000** [comment]
@Fabrizio-Caruso : That's why I suggested Mingw instead of Cygwin.
