### ISSUE TITLE
If you use register parameters you get even better results with CC65

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [iss000/oricCompilerBenchmark#3]
The `-r` option has no use without register parameters or variables.

In particular with CC65, it is usually worthwhile to use register with parameters (and even more with pointer parameters) when the parameter is used at least 3 times in the body of the function. This change won't affect the compatibility with the other compilers (unless they are totally broken).

For example if I only change the signature of `aes_shiftRows` by using `register` I get:
![image](https://user-images.githubusercontent.com/29057615/175697339-05cddd3d-292d-4098-be6b-64df336e0758.png)

I get a shorter aes256-cc65:
![image](https://user-images.githubusercontent.com/29057615/175697384-71af7513-88f7-41e2-ab57-cf5004f1d2e1.png)

**Comment by iss000** [comment]
The main goal is to compare compilers with the **same sources**. Of course there can be achieved better results but this is very individual to each compiler. Here as example adding 'register' will work for cc65 but maybe will break others compilers.
Else, thanks for feedback, will see how fix this asap.

**Comment by Fabrizio-Caruso** [comment]
The `register` keyword cannot break any compiler unless it is already badly broken.
The way `register` works is that is just a suggestion to the optimizer for variables that are "used a lot". It is just standard C. Nowadays most compilers do nothing with it. On the other hand, CC65 takes advantage of it.

I use `register` in my games written in C with Cross-Lib (which is my WORA framework, library and abstraction-layer: https://github.com/Fabrizio-Caruso/CROSS-LIB).
I compile the **very same** code containing some `register` parameters with more than a dozen native and cross-compilers including CC65, VBCC, recent native GCC, several modded GCC versions, CMOC, SDCC(ZSDCC), LCC (LCC1802), CC6303 and several others.

**Comment by iss000** [comment]
@Fabrizio-Caruso : I'm aware of your work ;).
