### ISSUE TITLE
Use LTO for llvm-mos

### ISSUE THREAD

**Issue by mysterymath** [iss000/oricCompilerBenchmark#5]
All of the SDK targets in llvm-mos default to using LTO, which is pretty essential for getting good results out of the compiler, and accordingly represents typical use of llvm-mos.

Without LTO, any calls out to a different translation must conservatively be assumed to recurse, which disables stack frame elision. With LTO, the whole program call graph can be walked, and stack laid out program-wide, with `__attribute__((leaf))` annotations in headers preventing ASM calls from disabling the optimization in the SDK.

This also allows unique zero-page regions to automatically be assigned to temporaries program wide, which can lift stack frames out of absolute memory entirely and into the zero page. This can also remove PHA/PLA sequences from function prologues/epilogues, since the registers being saved/restored can be rewritten to function-unique zero page locations, again program wide.

All this to say, LTO and the corresponding `-flto-zp` argument are "raison d'etre" features for llvm-mos and are completely transparent to typical users; benchmarking the compiler without them don't provide a very good indication of real-world performance.

**Comment by iss000** [comment]
Added **-flto**, great results! :)
With **-flto-zp** compilation fails, will check deeply asap but any suggestions?

**Comment by mysterymath** [comment]
Ah, is there a .zp section present in the linker script? `-flto-zp=<num bytes>` tells the compiler how many bytes of contiguous zero page is available (not counting the imaginary registers), but that just makes it place symbols in 
.zp sections to be assigned specific addresses layer by the linker.

EDIT: Ah, notably that's a compiler driver flag; for 'modern' toolchains the compiler driver (`clang` and `clang++`) typically adds a considerable amount of wrapping to the underlying compile and link invocations (e.g. all of the `-mllvm` flags in llvm-mos). To have this work with `lld` directly, you'd need to pass `-mllvm -zp-avail=<num bytes>` to it, since it's responsible for doing codegen and laying out the zero page. (The earlier compile steps will just emit LLVM IR in LTO mode.)

**Comment by iss000** [comment]
Added -flto-zp=224.
