### ISSUE TITLE
Shell scripts failing on debian 12

### ISSUE THREAD

**Issue by gorlik** [iss000/oricCompilerBenchmark#8]
The shell scripts used to invoke the compilers fail on debian with:
oricCompilerBenchmark/playground/share/cc65/x-cc.sh: 17: Bad substitution

This is because the ${ofile/.o/.s} is a bash extension and not supported by the default shell (/bin/sh which points to dash in debian)

There are 2 options to fix it:
change /bin/sh to /bin/bash in the scripts header
or
change the substitution to the POSIX compliant ${ofile%.c}.o

I can send a pull request with either change. Just let me know which you prefer.

**Comment by iss000** [comment]
Good catch! Please submit your PR!

**Comment by iss000** [comment]
Fixed with c1d4967.
